name: website deployment
on:
 push:
  branches: [master]
 
jobs:  
  build:
    name: build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          # The branch, tag or SHA to checkout. When checking out the repository that triggered a workflow, this defaults to the reference or SHA for that event.  Otherwise, uses the default branch
          ref: master
          token: ${{ secrets.GH_TOKEN }} 
          persist-credentials: true
          clean: true
          submodules: recursive
    
      - name: Pull and build the required resource-types submodules
        run: |
          git submodule update --init --recursive
          
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.4
        with:
          go-version: '^1.17.1' # The Go version to download
          stable: ' false'
      - name: Yarn Setup
        # You may pin to the exact commit or the version.
        # uses: DerYeger/yarn-setup-action@f55be5383ea94f5eb25b20aee609af4603a68dde
        uses: DerYeger/yarn-setup-action@v1.0.1
        
      - name: Run Yarn Install and Build
        env:
         GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
         ls -la
         
      - name: setup-docker
        # You may pin to the exact commit or the version.
        # uses: docker-practice/actions-setup-docker@51fd5009666ea5e3382fe125abf5d73d31386b59
        uses: docker-practice/actions-setup-docker@1.0.8
        with:
          # Docker Version
          docker_version: 20.10
          # Docker nightly Version
          # Docker Channel
          docker_channel: stable
          # Enable Buildx
          docker_buildx: true
          # docker cli experimental
          docker_cli_experimental: enabled
      - name: Test Docker   
        run: |
         docker version
         
      - name: Check Directory path
        run: |
         ls -la
               
      - name: Docker Compose Action
        # You may pin to the exact commit or the version.
        # uses: isbang/compose-action@fab6f72bef82b75de541a7b9da1d23412953c2bd
        uses: isbang/compose-action@v1.0.0
        with:
          # relative path to compose file
          compose-file: ./docker-compose.yml
          # additional options to pass to `docker-compose down` command
          down-flags: none
      - name: Run Docker Compose File to build project
        run: |
         ls -la
         docker-compose up --build --detach
         
      - name: Test the frontend
        run: |
         ls -la
         cd warehouse && yarn install && yarn test
        
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.GH_TOKEN }}
          # This is the branch you wish to deploy to, for example gh-pages or docs.
          branch: ten-resource-website
          # The folder in your repository that you want to deploy. If your build script compiles into a directory named build you would put it here. Folder paths cannot have a leading / or ./. If you wish to deploy the root directory you can place a . here.
          folder: .
      
          
      
         
      
      
      
