name: website deployment
on:
 push:
  branches: [master]
 
jobs:  
  build:    
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      
      - name: Pull and build the required resource-types submodules
        run: |
          git submodule update --init --recursive
          
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.4
        with:
          go-version: '^1.17.1' # The Go version to download
          stable: ' false'
         
      
      
      
